### ISSUE TITLE
Web: Blogpost QA Phase 2

### ISSUE THREAD

**Issue by tordans** [osmberlin/parkraum.osm-verkehrswende.org#16]
- [x] [Blogpost fertig](https://pads.ccc.de/gWd8DY3PJ6) @SupaplexOSM 
  - Symbolbild Parkbuchten (Mapilary Link?)
  - Siehe Gürtelstraße
- [x] Veröffentlichen @tordans 
- [x] Ergebnisse mit Simon besprechen @SupaplexOSM

**Comment by SupaplexOSM** [comment]
Bezüglich Symbolbild: Wir könnten noch etwas warten, bis die Carto-Kacheln [hier](https://www.openstreetmap.org/#map=19/52.50703/13.47127) neu generiert wurden - dann könnten wir ein vorher-nacher-carto-gif machen.

Ansonsten wäre hier ([OSM](https://www.openstreetmap.org/#map=19/52.50872/13.47257) | [Mapillary](https://www.mapillary.com/app/?pKey=569177870852094&lat=52.5082929&lng=13.4723255&z=17&focus=photo&x=0.2777632981014353&y=0.6493681640785228&zoom=0)) etwas weiter nördlich unser Testabschnitt - bereits aktuell gerendert.

**Comment by tordans** [comment]
Done: https://parkraum.osm-verkehrswende.org/posts/2022-09-09-stichprobenpruefung
