### ISSUE TITLE
Small improvement: Add legend to background map selection so that user knows how to toggle/untoggle maps

### ISSUE THREAD

**Issue by tifa365** [osmberlin/parkraum.osm-verkehrswende.org#20]
First I was under the impression the background maps were not loading, since I simply clicked on each map to load, as you would on different categories of a website's menu. Then I figured you would have to untoggle/unselect a map by clicking again. Some people might be familiar with this behavior but for the common user it would be nice to have a short explanation, such as "Einzelkarte durch Klicken auswählen und deselektieren" or similar.

**Comment by tordans** [comment]
We can close this ticket. We now use radverkehrsatlas.de to display and interact with the vector tile data. That application has a far better UX for background layer and such.

Links to the app are on the region pages https://parkraum.osm-verkehrswende.org/regions/berlin/

The Neukölln app is still a simpler map, but the layer switch works fine for that as well http://localhost:3000/project-prototype-neukoelln/data
