### ISSUE TITLE
Hannover Testgebiet

### ISSUE THREAD

**Issue by synchronisator** [osmberlin/parkraum.osm-verkehrswende.org#30]
Hallo, wir hatten neulich auf Twitter Kontakt.
Ich würde gerne etwas beitragen und in Hannover mein Stadtgebiet verbessern.
Aber ich bin alleine, ohne größere Gruppe und würde nur bei Spaziergängen u.ä. mappen können.
Deshalb bitte nicht zu viel Aufwand treiben für mich. Wenn es unverhältnismäßig ist, bitte auch einfach sagen.

Es ginge entweder erstmal ganz klein um meinen Wohnblock oder meinen Stadtteil.
Wohnblock: OSM-id: [31961153](https://www.openstreetmap.org/way/31961153)
Stadtteil: OSM-id: [3357529](https://www.openstreetmap.org/relation/3357529)
Danke

**Comment by synchronisator** [comment]
Super, vielen Dank.

**Comment by tordans** [comment]
Hallo @synchronisator jetzt sind wir (fast) soweit den Parkraum in Hannover darzustellen. Unten ein Update…
Aber vorab schonmal das Fazit: Es kann losgehen! Wir würden uns freuen, wenn ihr Hannover mit Parkraumdaten ausstattet und Feedback zum System gebt.

https://parkraum.osm-verkehrswende.org/regions/hannover/ ist die "Projektseite" für dein Gebiet mit Zahlen und – in den nächsten Woche – den Links für den Export der Daten

Dort ist auch die Karte verlinkt, wo du die prozessierten Daten sehen kann

Allerdings wirst du sehen, dass Hannover noch leer ist bzw. wenn du auf ["Stil: Vollständigkeit"](https://radverkehrsatlas.de/regionen/parkraum?lat=52.3783&lng=9.7313&zoom=13&theme=parking&bg=default&config=!(i~parking~topics~!(i~parking~a~~s~!(i~default~a~_F)(i~presence~a)(i~raw~a~_F))(i~parkingPoints~a~_F~s~!(i~default~a))(i~parkingAreas~a~~s~!(i~default~a)(i~position-separate~a~_F))(i~parkingDebug~a~_F~s~!(i~default~a))(i~parkingStats~a~_F~s~!(i~default~a~~filters~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F)))(i~length~a~_F~filters~!(i~admin*_level~o~!(i~*4~a~_F)(i~*9~a)(i~*10~a~_F))))(i~landuse~a~_F~s~!(i~default~a))(i~mapillaryCoverage~a~_F~s~!(i~default~a)))~) wechselst, dass keine Daten erkannt werden.

Es sieht so aus, dass ihr in Hannover noch vom alten auf das neue Schema wechseln müsst.  Dazu hat Alex einen Blogpost geschrieben https://www.openstreetmap.org/user/Supaplex030/diary/401053, wo er auch unser Tool zum Update der Tags erwähnt. 

Wenn ihr StreetComplete verwendet, würde das ebenfalls die Tags updaten.

Und [der Zlant-Editor](https://zlant.github.io/parking-lanes/#16/52.3891/9.7443) schreibt jetzt auch das neue Schema (und versteht auch das alte, stellt also die alten Daten auch dar).

Sobald Daten im neuen Schema auftauchen, kannst du die neue Ansicht "Parkraum Debug" in der Karte verwenden. Sie zeigt dann, wie die Prozessierung Elemente "ausstanzt"/"subtrahiert", die nicht mit gezählt werden.

Übrigens, auch neu sind die beiden Artikel Mitmachen https://parkraum.osm-verkehrswende.org/participate/ und FAQ https://parkraum.osm-verkehrswende.org/faq/ auf unserer Seite.

**Comment by synchronisator** [comment]
Hallo, ich bin dabei die Tags in Hannover zu updaten.
Dabei ist mir aufgefallen, dass bei einigen Flächen das Tag:
``
orientation = perpendicular
parking = street_side
`
statt
`
parking:orientation = perpendicular
parking = street_side
`
verwendet wird. Wie es scheint wird das dann nicht korrekt dargestellt.
Das sollte vllt auch berichtigt werden.

**Comment by synchronisator** [comment]
Und vllt noch eine Frage auch wenn sie hier nicht so richtig zum Topic gehört.
Wie habt ihr das mappen von Einfahrten und Vorwölbungen bei Seitenparkstreifen gemacht?
Das generelle Mappen wo wie geparkt werden darf geht ja mit StreetComplete gut.
Aber das MicroMapping all dieser Einfahrten, Bordsteinabsenkungen etc. geht da eher weniger gut.
Habt ihr da einen guten Vorschlag? 
Vllt Papierausdruck auf dem man unterwegs markiert und dann am PC übertragen?
Danke

**Comment by tordans** [comment]
> …
> orientation = perpendicular parking = street_side
> …

Verschoben in https://github.com/osmberlin/osm-parking-processing/issues/68. Gerne getrennte Themen in getrennte Issues. Danke fürs finden des Bugs!

**Comment by tordans** [comment]
> Aber das MicroMapping all dieser Einfahrten, Bordsteinabsenkungen etc. geht da eher weniger gut.
Habt ihr da einen guten Vorschlag?

Ich laufe mit GoMap!! rum und mappe die Einfahrten direkt vor Ort.

Man kann sich auch Geo Notes in Apps setzen und die dann als Layer in iD oder JOSM eintragen. Da gibts Workflows je nach System/Software, aber nichts super einfaches.

In Berlin haben wir außerdem guten städtische Daten, die man als Basis nutzen kann. Die haben wir auch in eine MapRoulette Challenge gepackt; aber das ist nicht so schön zu handeln.

Am einfachsten "fürs Sofa" ist IMO, vorher eine Befahrung mit GoPro Max zu machen und dann die 360° Bilder zu nutzen für das Mappen zu Hause. Damit kann man gut die Einfahrten erkennen. Eine GoPro haben wir zum Ausleihen https://wiki.openstreetmap.org/wiki/Berlin/Kameraverleih bei Bedarf (sie aber erst anderswo frei werden; müsste ich fragen).

Hoffe das hilft :-).

**Comment by synchronisator** [comment]
Ok, vielen Dank für die Infos. 
Ich war mir nicht sicher "wo" der Fehler lag. Deshalb hab ich da kein gesondertes Issue draus gemacht, aber mach ich nächstes mal :)

Aber ich stell hier trotzdem nochmal ein paar Fragen weil ich nicht weiß wo ich das sonst stellen soll. Oder gibt es ein Forum/Irc/Discord/o.ä.?

Wie mappt man am besten die "Vorwölbingen" bei Parkbuchten? 
Es ist dabei ja auch noch erlaubt vor der Vorwölbung parallel zu parken, wenn die Straßenbreite das zulässt. Insofern müsste man die Straße entsprechend unterbrechen und die abschnitte einzeln taggen.
Oder gibt es da eine einfachere Variante?

Zur Straßenbreite noch eine Frage.
Wenn kein Schild an der Straße steht, dann ist ja generell parken auf beiden Seiten, parallel erlaubt. Wenn die Straßenbreite aber zu gering ist, dann einigen sich die Anwohner ja meist auf eine Seite ohne, dass es angegeben ist.
Mappt man dann:
- beide Seiten als erlaubt und erfasst die Straßenbreite dazu sodass der Algorithmus erkennt, ob es beidseitig passt 
- "wechselseitiges Parken" (was wohl der Rechtslage am besten entspricht aber nicht der Realität)
- einseitiges Parken (was der Realität entspricht aber nicht der Rechtslage)?

Gibt es dazu vielleicht eine art Cheatsheet/Übersicht wie man mit den verschiedenen Situationen umgehen soll?
Sonst würde ich vllt anfangen sowas zusammenzustellen.

Vielen Dank!

**Comment by SupaplexOSM** [comment]
> Wie mappt man am besten die "Vorwölbingen" bei Parkbuchten?
> Es ist dabei ja auch noch erlaubt vor der Vorwölbung parallel zu parken, wenn die Straßenbreite das zulässt. Insofern müsste man die Straße entsprechend unterbrechen und die abschnitte einzeln taggen.
> Oder gibt es da eine einfachere Variante?

Solche Fälle sind ein bisschen komplizierter zu erfassen, aber nicht unmöglich. Eine ständige Aufteilung der Straßenlinie ist nicht nötig.

Für die Genauigkeit des Ergebnisses ist es generell vorteilhaft, Parkbuchten als separate Geometrie zu erfassen, wenn diese regelmäßig durch solche Verwölbungen unterbrochen sind (im Wiki gibt es ein paar [allgemeine Hinweise zum Mappen separater Geometrien](https://wiki.openstreetmap.org/wiki/DE:Street_parking#Separat_gemappte_Parkpl%C3%A4tze_im_Stra%C3%9Fenraum) dazu bzw. eine [Seite auch speziell für Parkbuchten](https://wiki.openstreetmap.org/wiki/DE:Tag:parking%3Dstreet_side)).

In dem von dir beschrieben Fall gelten dabei gewissermaßen zwei Parkregeln gleichzeitig: Einmal für die Parkbuchten (deren Attribute – z.B. `orientation` – du dann an der separaten Geometrie angibst), und einmal für die Fahrbahn. Es ist ok, der gesamten Fahrbahn z.B. "Parallelparken auf der Fahrbahn" zuzuordnen, denn die Parkbuchten "überschreiben" diese Regel an den Stellen, an denen sie existieren. Wenn es dann kein explizites `parking:*=separate` gibt, ist das nicht so schlimm.


> Wenn die Straßenbreite aber zu gering ist, dann einigen sich die Anwohner ja meist auf eine Seite ohne, dass es angegeben ist.

Dazu gibt es verschiedene "Philosophien", aber am praktischsten (und wahrscheinlich auch am verbreitetsten) ist es, die tatsächliche "traditionelle" Situation zu mappen. Denn häufig ist die "Einigung" der Anwohner ein ziemlich konstantes Ergebnis, was sich im Laufe der Jahre kaum ändert – zumindest sind das die Erfahungen, die ich hier in Berlin gemacht habe, wo wir auf jährliche Luftbilder aus dem letzten Jahrzehnt zurückgreifen können, auf denen man das gut sieht.

Also: Wenn alle quasi immer auf der einen Seite stehen und niemand auf der anderen, dann kann man das auch so mappen (z.B. `parking:right=lane`/`parking:right:orientation=parallel` + `parking:left=no`). Wenn mal hier, mal dort geparkt wird, wäre dann [`parking:both:staggered=yes`](https://wiki.openstreetmap.org/wiki/DE:Street_parking#Versetztes_Parken_auf_schmalen_Stra%C3%9Fen) die richtige Wahl (im Zweifelsfall kann man ja schauen, ob die vorgefundene Situation der gleichen wie auf einem Luftbild entspricht, dann hat man zumindest einen Anhaltspunkt, ob es da zeitliche Veränderungen gibt).


> Gibt es dazu vielleicht eine art Cheatsheet/Übersicht wie man mit den verschiedenen Situationen umgehen soll?
> Sonst würde ich vllt anfangen sowas zusammenzustellen.

Bisher gibt es vor allem die [allgemeine Wikiseite](https://wiki.openstreetmap.org/wiki/DE:Street_parking), die noch relativ jung ist und daher einige Aspekte noch eher vernachlässigt. Teils wurde sie für den "Community-Diskussionsprozess" auch noch bewusst etwas vage gehalten, da insbesondere solche Fragen, wie du sie hier aufgeworfen hast, bis vor kurzem noch relativ wenig ausdiskutiert waren. Das ändert sich zum Glück zur Zeit, sodass wir nach und nach konkretere Empfehlungen für Situationen wie diese hier formulieren können.

Wenn du so ein Cheat Sheet aufstellen willst, wäre das eigentlich ganz großartig, dann könnten wir das z.B. mit in die Wikiseite einfließen lassen!

**Comment by SupaplexOSM** [comment]
Das klingt gut. Was die Straßenbreite betrifft, gehe ich quasi genauso vor, allerdings haben wir in Berlin das Glück, Open Data ALKIS-Daten nutzen zu können, aus denen sich mit JOSM recht präzise die Fahrbahnbreite ableiten lässt oder im Zweifelsfall/bei veralteten Bildern geht das auch gut aus Luftbildern.

**Comment by tordans** [comment]
https://parkraum.osm-verkehrswende.org/regions/hannover/

**Comment by tordans** [comment]
@synchronisator  bei der Prozessierung ist uns aufgefallen, dass es noch highway=road ein paar Mal bei euch gibt. Vielleicht kannst du das mal umtaggen bei Gelegenheit. Mehr unter https://maproulette.org/browse/challenges/39479

<img width="640" alt="image" src="https://github.com/osmberlin/parkraum.osm-verkehrswende.org/assets/111561/7fca27f9-2d49-4e0b-8a1a-dc69856d0123">
