### ISSUE TITLE
Fehlende Information auf der "Statistik"-Seite

### ISSUE THREAD

**Issue by pingberlin** [osmberlin/parkraum.osm-verkehrswende.org#34]
Die Bezirke `Friedrichshain-Kreuzberg` und `Neukölln` waren fast vollständig gemappt.
Allerdings zeigen die statistischen Daten Werte von 0,4% - 1,5% an.
Siehe: https://parkraum.osm-verkehrswende.org/project-vector-tiles/dashboard

Könnt ihr bitte eine Information über den Statistiken anfügen, weshalb das so ist?

Mir ist als für das Projekt mappender unklar, ob Daten, die ich jetzt sammle, genauso verloren gehen könnten.

Herzlichen Dank

**Comment by tordans** [comment]
Hi @pingberlin danke für die Nachfrage. Keine Daten, die du einträgst, gehen verloren. Sie sind in der OpenStreetMap Datenbank gespeichert. Wir prozessieren diese Daten und erstellen einen prozessierten, getrennten Datensatz.

Zur Zeit sind wir in einer Umstellungsphase. Das Schema, nach dem Parkraum-Daten erfasst sind, wird gerade geändert.

Das Script auf der Webseite läuft noch nach altem Schema; die meisten Daten in Neukölln und Xhain sind aber schon "umformuliert" zum neuen Schema. Andere Teile der Welt aber noch nicht.

Unter https://parkraum.osm-verkehrswende.org/project-vector-tiles/#16/52.47928/13.4381 schreiben wir…
> 👉 Aktueller Hinweis: Das Parkraumschema in OpenStreetMap wird derzeit erneuert. Daher werden derzeit nicht alle verfügbaren Daten angezeigt.

(Wenn Du ein Segment anklickst.)

Um es klarer zu machen sollten wir tun:

- [ ] Die Info zur Schema-Migration auch auf die Statistik-Seite anzeigen; ggf. Link nach hier.

Danke fürs Mit-Mappen!
Für den Übergang kannst du dort, wo du noch nicht gemapped hast, weiter nach dem alten Schema mappen. Dort, wo schon etwas war, am besten abwarten, bis das Tooling (bspw. StreetComplete) aktualisiert wurde.

**Comment by SupaplexOSM** [comment]
Danke @pingberlin für deine Mitarbeit!

Da nun auch das Parkraum-Overlay des OSM-Editors StreetComplete auf das neue Parkraumschema umgestellt wurde, kann ab nun die systematische Aktualisierung der bestehenden, nach dem vorherigen Schema erfassten Parkraumdaten stattfinden. Weiterhin gehen keine Daten verloren, sie sind aber in Teilen für Auswertungen wie unsere vielleicht noch ein paar Wochen "unsichtbar", bis sie aktualisiert wurden.

Unser Script arbeitet nun mit dem neuen Schema, was dazu geführt hat, dass sich die Karte "umgedreht" hat: Nun sind vor allem Neukölln und Friedrichshain-Kreuzberg "grün" zu sehen, während die anderen Bezirke größtenteils leer bleiben (in denen noch überwiegend das alte Schema zu finden ist).

Ich habe auf der [Statistik-Seite](https://parkraum.osm-verkehrswende.org/project-vector-tiles/dashboard/) einen Hinweis eingefügt, der auf die Datenumstellung eingeht – dort ist auch ein Blogpost verlinkt, der beschreibt, wie man bei der Aktualisierung der Daten in OSM helfen kann. (FunFact: Die Ermittlung der Prozentwerte dort basiert gerade aus irgendeinem Grund noch auf den alten Daten...)
