### ISSUE TITLE
Update Leaflet

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/parkraum.osm-verkehrswende.org#36]
Je nach Browser/Betriebssystem scrollt die Karte mit dem Mausrad um zwei statt einer Zoomstufe. Mit einer neuen Leaflet-Version sollte das gefixt sein.

**Comment by tordans** [comment]
@SupaplexOSM wir verwenden seit einer Weile Leaflet 1.9.3

Besteht das Problem noch? Sonst gerne schließen.

**Comment by SupaplexOSM** [comment]
Nein, das Problem besteht seit einiger Zeit nicht mehr – zumindest nicht bei mir. Ich gehe davon aus, dass es seit dem Update funktioniert.

@tordans FYI: Bei der [Straßenraumkarte](https://strassenraumkarte.osm-berlin.org/?map=micromap) besteht das Problem aber weiterhin – vielleicht hast du mal die Muße, hier auch ein Leaflet-Update einzuspielen (gerade [Issue dafür angelegt](https://github.com/SupaplexOSM/strassenraumkarte-neukoelln/issues/18)).
