### ISSUE TITLE
Gebiet Bonn

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/parkraum.osm-verkehrswende.org#43]
In [Bonn](https://www.openstreetmap.org/relation/62508) gibt es recht viele Daten nach neuem Schema und mindestens zwei aktive Parkraummapper. Würde sich daher als neue Region anbieten.

**Comment by tordans** [comment]
Bonn ist seit einer Weile hinzugefügt https://parkraum.osm-verkehrswende.org/regions/bonn/
