### ISSUE TITLE
map don't work in mobile view

### ISSUE THREAD

**Issue by gislars** [osmberlin/parkraum.osm-verkehrswende.org#5]
using a mobile device, the maps aren't visible
![Bildschirmfoto vom 2022-06-26 13-00-12](https://user-images.githubusercontent.com/402166/175811074-b7a942c9-f63b-4730-bd72-4684e6903e48.png)

**Comment by tordans** [comment]
# Conclusion

- https://parkraum.osm-verkehrswende.org/project-prototype-neukoelln/?map=parkingmap#18/52.47379/13.44164 has an improved mobile and tablet view
- Mobile optimizations for atlas-app is tracked privately in https://github.com/FixMyBerlin/private-issues/issues/576
