### ISSUE TITLE
Gebiet Bietigheim-Bissingen

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/parkraum.osm-verkehrswende.org#51]
Rund um den Bahnhof wurde für die Kommune Parkraum gemappt: https://www.openstreetmap.org/relation/405807

**Comment by gislars** [comment]
Bietigheim-Bissingen habe ich hinzugefügt und wird bereits auf dem Server prozessiert. 

Nächster Schritt: 
- [ ] Webseite aktualisieren @tordans

**Comment by tordans** [comment]
Done, siehe https://parkraum.osm-verkehrswende.org/regions/bietigheim_bissingen/
