### ISSUE TITLE
Liste der Regionen alphabetisch anordnen

### ISSUE THREAD

**Issue by SupaplexOSM** [osmberlin/parkraum.osm-verkehrswende.org#58]
Da die Liste der Städte/Regionen mit verfügbaren Parkraumkarten in der linken Seitenleiste immer länger wird, könnten wir sie mal anders anordnen – fürs Erste reicht wahrscheinlich alphabetisch.

**Comment by tordans** [comment]
Ist eingebaut, geht gleich online.
